#base image
FROM node:16-alpine

#work dir
#WORKDIR /usr/frontend
WORKDIR /app

#copying the node modules
COPY package.json ./

#install npm
RUN npm install

#change the permission of the node_modules from root to node
RUN chown -R node:node /app/node_modules

#copy other files
COPY ./ ./

#run command
CMD ["npm", "run", "start"]
